# Generated by Django 2.2.10 on 2021-07-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='última modificación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre ')),
                ('surname1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('surname2', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('identification', models.CharField(max_length=11, verbose_name='Carnet')),
                ('birthday_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('create_uid', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('write_uid', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'app_person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.PersonModel')),
                ('year', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('post', 'Posgrado')], max_length=50, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'app_student',
                'managed': True,
            },
            bases=('app.personmodel',),
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.PersonModel')),
                ('type', models.CharField(choices=[('fixed', 'Fijo'), ('contract', 'Contrato')], max_length=50, verbose_name='Tipo trabajador')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'app_worker',
                'managed': True,
            },
            bases=('app.personmodel',),
        ),
    ]
