# Generated by Django 2.2.10 on 2021-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210720_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='is_social_service',
            field=models.BooleanField(default=False, verbose_name='Servicio social'),
        ),
    ]
