# Generated by Django 2.2.10 on 2021-07-22 03:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_workermodel_is_social_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='última modificación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('create_uid', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('write_uid', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'app_area',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='identification',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El carnet debe contener 11 dígitos', regex='(^[\\d]{11}$)')], verbose_name='Carnet'),
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='última modificación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app.AreaModel', verbose_name='Área')),
                ('create_uid', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('write_uid', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'app_department',
                'managed': True,
            },
        ),
    ]
