# Generated by Django 2.2.10 on 2021-07-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210722_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='identification_image_front',
            field=models.FileField(blank=True, null=True, upload_to='identification_image_front', verbose_name='Foto carnet amberso'),
        ),
    ]
