# Generated by Django 2.2.10 on 2021-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210723_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='type',
            field=models.CharField(blank=True, choices=[('person', 'Persona'), ('trabajador', 'Trabajador'), ('estudiante', 'Estudiante')], max_length=50, null=True, verbose_name='Tipo Categoría'),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='app.CategoryModel', verbose_name='Categorías'),
        ),
    ]
