# Generated by Django 2.2.10 on 2021-07-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210723_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='type',
            field=models.CharField(blank=True, choices=[('person', 'Persona'), ('worker', 'Trabajador'), ('student', 'Estudiante')], max_length=50, null=True, verbose_name='Tipo Categoría'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'worker'}, null=True, to='app.CategoryModel', verbose_name='Categorías'),
        ),
    ]
